name: SonarQube Scan
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
  merge_group:

permissions:
  contents: read

jobs:
  sonarqube:
    uses: mauhlik/reusable-workflows/.github/workflows/sonarqube-scan.yml@v1
    secrets: inherit
